// Generated by gencpp from file a_star/isReached.msg
// DO NOT EDIT!


#ifndef A_STAR_MESSAGE_ISREACHED_H
#define A_STAR_MESSAGE_ISREACHED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a_star
{
template <class ContainerAllocator>
struct isReached_
{
  typedef isReached_<ContainerAllocator> Type;

  isReached_()
    : Reached(false)  {
    }
  isReached_(const ContainerAllocator& _alloc)
    : Reached(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Reached_type;
  _Reached_type Reached;





  typedef boost::shared_ptr< ::a_star::isReached_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a_star::isReached_<ContainerAllocator> const> ConstPtr;

}; // struct isReached_

typedef ::a_star::isReached_<std::allocator<void> > isReached;

typedef boost::shared_ptr< ::a_star::isReached > isReachedPtr;
typedef boost::shared_ptr< ::a_star::isReached const> isReachedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a_star::isReached_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a_star::isReached_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::a_star::isReached_<ContainerAllocator1> & lhs, const ::a_star::isReached_<ContainerAllocator2> & rhs)
{
  return lhs.Reached == rhs.Reached;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::a_star::isReached_<ContainerAllocator1> & lhs, const ::a_star::isReached_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace a_star

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::a_star::isReached_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_star::isReached_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_star::isReached_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_star::isReached_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_star::isReached_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_star::isReached_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a_star::isReached_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c2e8beeec8a67b9955f2207bd7a9654";
  }

  static const char* value(const ::a_star::isReached_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c2e8beeec8a67b9ULL;
  static const uint64_t static_value2 = 0x955f2207bd7a9654ULL;
};

template<class ContainerAllocator>
struct DataType< ::a_star::isReached_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a_star/isReached";
  }

  static const char* value(const ::a_star::isReached_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a_star::isReached_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Reached\n"
;
  }

  static const char* value(const ::a_star::isReached_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a_star::isReached_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isReached_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a_star::isReached_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a_star::isReached_<ContainerAllocator>& v)
  {
    s << indent << "Reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // A_STAR_MESSAGE_ISREACHED_H
